### PR TITLE
fix: force the optimize for speed flag for styled-jsx based on env

### PR DESCRIPTION
**Pull request by varl**
We have the same problem in ui-widgets[1], so this should work here as
well.

[1] https://github.com/dhis2/ui-widgets/commit/7202a0ac2eacf5204821ffbaa2ce90012c8fcc4f

### CODE REVIEW

**Review by Mohammer5 — APPROVED** [review]
Ahhh I already forgot about this one. Thank @varl

**Comment by varl** [comment]
@Mohammer5 did you verify it fixes it?

**Comment by Mohammer5** [comment]
Good catch.. Interestingly it seems to work for `ui-core` styles.
CssReset and components used in stories have all their styles applied.
The global FrameStyleWrapper decorator does not though (which is very weird to me, because everything else seems to work):

```
stylesheet.js:157 StyleSheet: illegal rule: 
html{height:100%;}body{height:100%;min-height:100%;}#root{height:100%;padding:16px;}
See https://stackoverflow.com/q/20007992 for more info
```

**Comment by varl** [comment]
Ok, looks like the styled-jsx `css` import was missing from the `FrameStylesWrapper` file as well. How do you reproduce the issue? I see the styles getting adding to `#root`, `body`, and `html` now.

**Comment by Mohammer5** [comment]
@varl That doesn't do the trick (it's never been required to import `css` in storybook files for whatever reason..)

I reproduce it by
* yarn start
* go to localhost:5000 in chrome
* go to RadioGroup Default story
* Hard refresh page

FrameStyleWrapper styled throw the error

**Comment by varl** [comment]
> @varl That doesn't do the trick (it's never been required to import `css` in storybook files for whatever reason..)

We do it in core and widgets though, maybe it's a no-op:

- https://github.com/dhis2/ui-core/blob/master/.storybook/frame-styles-decorator.js#L2
- https://github.com/dhis2/ui-widgets/blob/master/.storybook/frame-styles-decorator.js#L2

Debugging this some more it only affects the `RadioGroup`, the other components work fine when following your steps to reproduce. Something seems to be funky in `RadioGroup` component.

**Comment by Mohammer5** [comment]
@varl I did that already, the difference is:
Only the radiogroup is using `ui-core` components

**Comment by varl** [comment]
> @varl I did that already, the difference is:
> Only the radiogroup is using `ui-core` components

Ah. OK. 🤔 

There's something going on, initially `optimizeForSpeed` is set correctly, but on re-rendering a component the property changes to `true` which causes subsequent components to fail.

**Comment by varl** [comment]
I cannot reproduce this in anymore, @Mohammer5 take another pass? I left the comment next to the `true` to indicate that we might want to figure this out at some point.

**Comment by Mohammer5** [comment]
> I cannot reproduce this in anymore

Confirmed

**Pull request merged**
